<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit9fc8de35a5df3e26064d578c5d420bae
{
    public static $prefixLengthsPsr4 = array (
        'F' => 
        array (
            'FacebookAds\\' => 12,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'FacebookAds\\' => 
        array (
            0 => __DIR__ . '/..' . '/facebook/php-ads-sdk/src/FacebookAds',
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit9fc8de35a5df3e26064d578c5d420bae::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit9fc8de35a5df3e26064d578c5d420bae::$prefixDirsPsr4;

        }, null, ClassLoader::class);
    }
}
